[package]
name = "generate_message"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = {path = "../constants", default-features = false, features = ["active"]}
db_handling = {path = "../db_handling", default-features = false, features = ["active"]}
definitions = {path = "../definitions", default-features = false, features = ["active"]}
hex = "0.4.3"
jsonrpsee = {version = "0.9.0", features = ["ws-client"]}
parity-scale-codec = "3.0.0"
qrcode_rtx = {path = "../qrcode_rtx"}
serde_json = "1.0.79"
sled = "0.34.6"
sp-core = {git = "https://github.com/paritytech/substrate", default-features = false, features = ["full_crypto"]}
tokio = { version = "1", features = ["full"] }
