[package]
name = "transaction_parsing"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.1.0"
bitvec = "0.20.4"
blake2-rfc = "0.2.18"
frame-metadata = "13.0.0"
hex = "0.4.3"
lazy_static = "1.4.0"
meta_reading = {path = "../meta_reading"}
parity-scale-codec = "2.1.1"
parity-scale-codec-derive = "2.1.0"
regex = "1.4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
sp-arithmetic = "3.0.0"
sp-runtime = "3.0.0"
