[package]
name = "transaction_parsing"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.0"
constants = {path = "../constants"}
db_handling = {path = "../db_handling"}
definitions = {path = "../definitions"}
frame-metadata = {version = "15.0.0", default-features = false}
hex = "0.4.3"
parity-scale-codec = "3.0.0"
parser = {path = "../parser"}
plot_icon = {git = "https://github.com/varovainen/polkadot-identicon-rust", default-features = false, features = ["pix"]}
sled = "0.34.6"
sp-core = {version = "6.0.0", default-features = false, features = ["full_crypto"]}
sp-runtime = {version = "6.0.0", default-features = false}

[lib]
name = "transaction_parsing"
crate-type = ["lib"]
