[workspace]

members = [
	"constants",
	"db_handling",
	"defaults",
	"definitions",
	"generate_message",
	"meta_reading",
	"printing_balance",
	"qr_reader_pc",
	"qr_reader_phone",
	"qrcode_rtx",
	"qrcode_static",
	"signer",
	"transaction_parsing",
	"transaction_signing"
]
