[package]
name = "db_handling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2-rfc = "0.2.18"
chrono = "0.4.19"
constants = {path = "../constants"}
defaults = {path = "../defaults"}
definitions = {path = "../definitions"}
hex = "0.4.3"
lazy_static = "1.4.0"
parity-scale-codec = {version = "3.0.0", features = ["derive"]}
plot_icon = {git = "https://github.com/varovainen/polkadot-identicon-rust", default-features = false, features = ["pix"]}
png = "0.17.3"
qrcode_static = {path = "../qrcode_static"}
regex = "1.5.4"
sled = "0.34.6"
sp-core = {version = "6.0.0", default-features = false, features = ["full_crypto"]}
sp-runtime = {version = "6.0.0", default-features = false}
tiny-bip39 = { version = "0.8.0", default-features = false }
zeroize = "1.5.3"

[lib]
name = "db_handling"
crate-type = ["lib"]
